#!/usr/bin/env bash
set -Eeuo pipefail

readonly ROOT=/root/oneplus15boot
readonly SOURCE_ROOT="$ROOT/build/source"
readonly KP="$SOURCE_ROOT/kernel_platform"
readonly COMMON="$KP/common"
readonly PATCH_ROOT="$ROOT/github-ci/patches"
readonly STOCK_CONFIG="$ROOT/inputs/stock-running.config"
readonly STOCK_IMAGE="$ROOT/artifacts/boot-audit/original/kernel"
readonly OUT="$ROOT/artifacts/gki-r53"
readonly STOCK_CERT="$OUT/stock-module-signing.der"
readonly STOCK_CERT_PEM="$COMMON/certs/oneplus-stock-gki.pem"
readonly STOCK_CERT_SHA256=F28DBCC60085B21A3CFF1342482897FA640B468847473147834F26C4FEB2DF43
readonly DIST="$OUT/dist"
readonly LOG="$ROOT/logs/build-gki-r53.log"
readonly STOCK_COMMIT=b2a876903b495c444a94b16f50d1463ffe953957
readonly STOCK_BUILD_NUMBER=14541642

mkdir -p "$OUT" "$DIST" "$(dirname "$LOG")"
exec > >(tee "$LOG") 2>&1

echo "Started: $(date --iso-8601=seconds)"
echo "CPUs: $(nproc)"
echo "Exact stock GKI commit: $STOCK_COMMIT"
df -h "$ROOT"

apply_patch_once() {
    local repository="$1"
    local patch_file="$2"
    if git -C "$repository" apply --check "$patch_file"; then
        git -C "$repository" apply "$patch_file"
        echo "Applied: $(basename "$patch_file")"
    elif git -C "$repository" apply --reverse --check "$patch_file"; then
        echo "Already applied: $(basename "$patch_file")"
    else
        echo "Patch does not apply cleanly: $patch_file" >&2
        exit 1
    fi
}

cd "$COMMON"
git remote get-url aosp >/dev/null 2>&1 || \
    git remote add aosp https://android.googlesource.com/kernel/common
git cat-file -e "$STOCK_COMMIT^{commit}" 2>/dev/null || \
    git fetch aosp "$STOCK_COMMIT"

# Preserve every previous experimental source edit in a recoverable stash.
if [[ -n "$(git status --porcelain)" ]]; then
    git diff > "$OUT/previous-source-edits.patch"
    git stash push -u -m "pre-exact-gki-r53-$(date +%Y%m%d-%H%M%S)"
fi
git checkout --detach "$STOCK_COMMIT"

apply_patch_once "$COMMON" "$PATCH_ROOT/001.GKI-6.12-or-above-fix_sysvipc_kabi.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/002.oneplus15-gki-droidspaces-config.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/003.export-ipc-namespace-symbols-for-rust-binder.patch"

# Keep MODULE_SIG_PROTECT enabled and trust the public certificate embedded in
# the exact stock kernel. This lets the replacement GKI authenticate OnePlus'
# prebuilt system_dlkm/vendor_dlkm modules (Wi-Fi, Bluetooth, etc.) without
# weakening signature enforcement or requiring the unavailable private key.
python3 - "$STOCK_IMAGE" "$STOCK_CERT" <<'PY'
import pathlib
import sys

image = pathlib.Path(sys.argv[1]).read_bytes()
needle = b"Build time autogenerated kernel key"
subject = image.find(needle)
if subject < 0:
    raise SystemExit("stock module-signing certificate subject was not found")

candidates = []
for start in range(max(0, subject - 1024), subject):
    if image[start:start + 2] != b"\x30\x82":
        continue
    length = int.from_bytes(image[start + 2:start + 4], "big") + 4
    if start + length <= len(image) and start <= subject < start + length:
        candidates.append((start, length))

if not candidates:
    raise SystemExit("stock module-signing DER certificate was not found")
start, length = max(candidates, key=lambda item: item[1])
pathlib.Path(sys.argv[2]).write_bytes(image[start:start + length])
print(f"Extracted stock certificate: offset={start} length={length}")
PY

actual_cert_sha256="$(openssl x509 -inform DER -in "$STOCK_CERT" \
    -noout -fingerprint -sha256 | sed 's/^.*=//; s/://g')"
test "$actual_cert_sha256" = "$STOCK_CERT_SHA256"
openssl x509 -inform DER -in "$STOCK_CERT" -out "$STOCK_CERT_PEM"
openssl x509 -inform DER -in "$STOCK_CERT" \
    -noout -subject -issuer -serial -fingerprint -sha256 \
    > "$OUT/stock-module-signing-certificate.txt"

# The retained OnePlus Kleaf fork expects the OEM-only vmlinux_oki artifact.
# Stock GKI r53 intentionally emits normal vmlinux, so remove only that stale
# output declaration; this does not alter kernel code or configuration.
apply_patch_once "$SOURCE_ROOT" \
    "$PATCH_ROOT/004.aosp-gki-drop-oneplus-vmlinux-oki-output.patch"
apply_patch_once "$SOURCE_ROOT" \
    "$PATCH_ROOT/005.aosp-gki-remove-oneplus-oki-release-infix.patch"

test "$(git rev-parse HEAD)" = "$STOCK_COMMIT"
git diff --check
git diff > "$OUT/source-changes.patch"

cd "$KP"
tools/bazel build --//build/kernel/kleaf:zstd_dwarf_compression \
    //common:kernel_aarch64_config
config_out="$(find -L bazel-bin/common/kernel_aarch64_config -type f -name .config -print -quit)"
test -n "$config_out"
cp "$config_out" "$OUT/config.before-build"

for symbol in SYSVIPC POSIX_MQUEUE IPC_NS PID_NS DEVTMPFS VIRTUALIZATION KVM; do
    grep -qx "CONFIG_${symbol}=y" "$config_out"
done
grep -qx '# CONFIG_USER_NS is not set' "$config_out"
grep -qx 'CONFIG_MODULE_SIG_PROTECT=y' "$config_out"
grep -qx 'CONFIG_SYSTEM_TRUSTED_KEYS="certs/oneplus-stock-gki.pem"' "$config_out"

# Avoid carrying the optional netfilter/IP-set experiment into this recovery
# candidate. The goal is the smallest possible delta from the running stock GKI.
for symbol in IP_SET NETFILTER_XT_SET NETFILTER_XT_MATCH_RECENT TMPFS_POSIX_ACL; do
    if grep -qx "CONFIG_${symbol}=y" "$config_out" && \
       ! grep -qx "CONFIG_${symbol}=y" "$STOCK_CONFIG"; then
        echo "Unexpected optional CONFIG_${symbol}=y" >&2
        exit 1
    fi
done

export MAKEFLAGS="-j$(nproc)"
export LLVM_PARALLEL_LINK_JOBS="$(nproc)"
export KBUILD_BUILD_USER=kleaf
export KBUILD_BUILD_HOST=build-host
export BUILD_NUMBER="$STOCK_BUILD_NUMBER"

rm -rf "$DIST"
mkdir -p "$DIST"
tools/bazel run --config=release \
    --//build/kernel/kleaf:zstd_dwarf_compression \
    //common:kernel_aarch64_dist -- \
    --destdir="$DIST"

test -s "$DIST/Image"
"$COMMON/scripts/extract-ikconfig" "$DIST/Image" > "$OUT/kernel.config"
for symbol in SYSVIPC POSIX_MQUEUE IPC_NS PID_NS DEVTMPFS VIRTUALIZATION KVM; do
    grep -qx "CONFIG_${symbol}=y" "$OUT/kernel.config"
done
grep -qx '# CONFIG_USER_NS is not set' "$OUT/kernel.config"
grep -qx 'CONFIG_MODULE_SIG_PROTECT=y' "$OUT/kernel.config"
grep -qx 'CONFIG_SYSTEM_TRUSTED_KEYS="certs/oneplus-stock-gki.pem"' "$OUT/kernel.config"

mkdir -p "$OUT/config-diff-final"
python3 - "$STOCK_CONFIG" "$OUT/kernel.config" \
    "$OUT/config-diff-final/value-changes.txt" <<'PY'
import pathlib
import re
import sys

def read_config(path):
    values = {}
    order = []
    for line in pathlib.Path(path).read_text().splitlines():
        match = re.fullmatch(r"(CONFIG_[A-Z0-9_]+)=(.*)", line)
        if match:
            key, value = match.groups()
        else:
            match = re.fullmatch(r"# (CONFIG_[A-Z0-9_]+) is not set", line)
            if not match:
                continue
            key, value = match.group(1), "n"
        if key not in values:
            order.append(key)
        values[key] = value
    return values, order

stock, stock_order = read_config(sys.argv[1])
new, new_order = read_config(sys.argv[2])
keys = stock_order + [key for key in new_order if key not in stock]
lines = []
for key in keys:
    before = stock.get(key, "<absent>")
    after = new.get(key, "<absent>")
    if before != after:
        lines.append(f"{key}: {before} -> {after}")
pathlib.Path(sys.argv[3]).write_text("\n".join(lines) + "\n")
PY

# Prove that the rebuilt kernel embeds and trusts the original OnePlus public
# certificate. A different autogenerated build certificate may also be present.
stock_cert_der="$(base64 -w0 "$STOCK_CERT")"
python3 - "$DIST/Image" "$stock_cert_der" <<'PY'
import base64
import pathlib
import sys

image = pathlib.Path(sys.argv[1]).read_bytes()
certificate = base64.b64decode(sys.argv[2])
if certificate not in image:
    raise SystemExit("stock module-signing certificate is missing from Image")
print("Verified: stock module-signing certificate is embedded in Image")
PY

for name in Image Image.lz4 Image.gz System.map Module.symvers vmlinux \
            vmlinux.symvers abi_symbollist; do
    [[ -f "$DIST/$name" ]] && cp "$DIST/$name" "$OUT/$name"
done

strings "$OUT/Image" > "$OUT/Image.strings"
grep -m1 '^Linux version 6\.12\.23-android16-5-' "$OUT/Image.strings" \
    > "$OUT/kernel-version.txt"
rm "$OUT/Image.strings"
git rev-parse HEAD > "$OUT/source-commit.txt"
git status --short --branch > "$OUT/source-status.txt"
(cd "$OUT" && sha256sum Image kernel.config kernel-version.txt \
    source-changes.patch source-commit.txt > SHA256SUMS.txt)

echo "Finished: $(date --iso-8601=seconds)"
cat "$OUT/kernel-version.txt"
cat "$OUT/SHA256SUMS.txt"
