#!/usr/bin/env bash
# Reproduce the separate USER_NS/NTSYNC gaming test kernel.
set -Eeuo pipefail

readonly ROOT=/root/oneplus15boot
readonly VARIANT="${VARIANT:-kabi-pointer-state-gaming-userns-ntsync}"
readonly EXTRA_PATCH="${EXTRA_PATCH:-010.allocate-sysvshm-task-state.patch}"
readonly POST_PATCH="${POST_PATCH:-012.guard-oplus-child-pidns-vendor-callbacks.patch}"
readonly GAMING_PATCH="013.enable-gaming-userns-ntsync.patch"
readonly SOURCE_ROOT="$ROOT/build/source"
readonly KP="$SOURCE_ROOT/kernel_platform"
readonly COMMON="$KP/common"
readonly PATCH_ROOT="$ROOT/github-ci/patches"
readonly STOCK_CONFIG="$ROOT/inputs/stock-running.config"
readonly STOCK_IMAGE="$ROOT/artifacts/boot-audit/original/kernel"
readonly OUT="$ROOT/artifacts/gki-r53-$VARIANT"
readonly STOCK_CERT="$OUT/stock-module-signing.der"
readonly STOCK_CERT_PEM="$COMMON/certs/oneplus-stock-gki.pem"
readonly STOCK_CERT_SHA256=F28DBCC60085B21A3CFF1342482897FA640B468847473147834F26C4FEB2DF43
readonly DIST="$OUT/dist"
readonly LOG="$ROOT/logs/build-gki-r53-$VARIANT.log"
readonly STOCK_COMMIT=b2a876903b495c444a94b16f50d1463ffe953957
readonly STOCK_BUILD_NUMBER=14541642

mkdir -p "$OUT" "$DIST" "$(dirname "$LOG")"
exec > >(tee "$LOG") 2>&1

echo "Started: $(date --iso-8601=seconds)"
echo "CPUs: $(nproc)"
echo "Exact stock GKI commit: $STOCK_COMMIT"
df -h "$ROOT"

apply_patch_once() {
	local repository="$1"
	local patch_file="$2"
	if git -C "$repository" apply --check "$patch_file"; then
		git -C "$repository" apply "$patch_file"
		echo "Applied: $(basename "$patch_file")"
	elif git -C "$repository" apply --reverse --check "$patch_file"; then
		echo "Already applied: $(basename "$patch_file")"
	else
		echo "Patch does not apply cleanly: $patch_file" >&2
		exit 1
	fi
}

cd "$COMMON"
if [[ -n "$(git status --porcelain)" ]]; then
	git diff > "$OUT/previous-source-edits.patch"
	git stash push -u -m "pre-gki-r53-$VARIANT-$(date +%Y%m%d-%H%M%S)"
fi
git checkout --detach "$STOCK_COMMIT"

apply_patch_once "$COMMON" "$PATCH_ROOT/001.GKI-6.12-or-above-fix_sysvipc_kabi.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/006.align-sysvipc-task-fields.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/007.use-task-kabi-reserves-for-sysvipc.patch"
if [[ -n "$EXTRA_PATCH" ]]; then
	apply_patch_once "$COMMON" "$PATCH_ROOT/$EXTRA_PATCH"
fi
if [[ -n "$POST_PATCH" ]]; then
	apply_patch_once "$COMMON" "$PATCH_ROOT/$POST_PATCH"
fi
apply_patch_once "$COMMON" "$PATCH_ROOT/002.oneplus15-gki-droidspaces-config.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/003.export-ipc-namespace-symbols-for-rust-binder.patch"
apply_patch_once "$COMMON" "$PATCH_ROOT/$GAMING_PATCH"

python3 - "$STOCK_IMAGE" "$STOCK_CERT" <<'PY'
import pathlib
import sys

image = pathlib.Path(sys.argv[1]).read_bytes()
needle = b"Build time autogenerated kernel key"
subject = image.find(needle)
if subject < 0:
    raise SystemExit("stock module-signing certificate subject was not found")
candidates = []
for start in range(max(0, subject - 1024), subject):
    if image[start:start + 2] != b"\x30\x82":
        continue
    length = int.from_bytes(image[start + 2:start + 4], "big") + 4
    if start + length <= len(image) and start <= subject < start + length:
        candidates.append((start, length))
if not candidates:
    raise SystemExit("stock module-signing DER certificate was not found")
start, length = max(candidates, key=lambda item: item[1])
pathlib.Path(sys.argv[2]).write_bytes(image[start:start + length])
print(f"Extracted stock certificate: offset={start} length={length}")
PY

actual_cert_sha256="$(openssl x509 -inform DER -in "$STOCK_CERT" -noout -fingerprint -sha256 | sed 's/^.*=//; s/://g')"
test "$actual_cert_sha256" = "$STOCK_CERT_SHA256"
openssl x509 -inform DER -in "$STOCK_CERT" -out "$STOCK_CERT_PEM"

apply_patch_once "$SOURCE_ROOT" "$PATCH_ROOT/004.aosp-gki-drop-oneplus-vmlinux-oki-output.patch"
apply_patch_once "$SOURCE_ROOT" "$PATCH_ROOT/005.aosp-gki-remove-oneplus-oki-release-infix.patch"

test "$(git rev-parse HEAD)" = "$STOCK_COMMIT"
git diff --check
git diff > "$OUT/source-changes.patch"

cd "$KP"
tools/bazel build --//build/kernel/kleaf:zstd_dwarf_compression //common:kernel_aarch64_config
config_out="$(find -L bazel-bin/common/kernel_aarch64_config -type f -name .config -print -quit)"
test -n "$config_out"
cp "$config_out" "$OUT/config.before-build"
for symbol in SYSVIPC POSIX_MQUEUE IPC_NS PID_NS USER_NS DEVTMPFS NTSYNC VIRTUALIZATION KVM; do
	grep -qx "CONFIG_${symbol}=y" "$config_out"
done
grep -qx 'CONFIG_MODULE_SIG_PROTECT=y' "$config_out"
grep -qx 'CONFIG_SYSTEM_TRUSTED_KEYS="certs/oneplus-stock-gki.pem"' "$config_out"
grep -qx 'CONFIG_RANDSTRUCT_NONE=y' "$config_out"

export MAKEFLAGS="-j$(nproc)"
export LLVM_PARALLEL_LINK_JOBS="$(nproc)"
export KBUILD_BUILD_USER=kleaf
export KBUILD_BUILD_HOST=build-host
export BUILD_NUMBER="$STOCK_BUILD_NUMBER"

rm -rf "$DIST"
mkdir -p "$DIST"
tools/bazel run --config=release --//build/kernel/kleaf:zstd_dwarf_compression //common:kernel_aarch64_dist -- --destdir="$DIST"

test -s "$DIST/Image"
"$COMMON/scripts/extract-ikconfig" "$DIST/Image" > "$OUT/kernel.config"
for symbol in SYSVIPC POSIX_MQUEUE IPC_NS PID_NS USER_NS DEVTMPFS NTSYNC VIRTUALIZATION KVM; do
	grep -qx "CONFIG_${symbol}=y" "$OUT/kernel.config"
done
grep -qx 'CONFIG_MODULE_SIG_PROTECT=y' "$OUT/kernel.config"
grep -qx 'CONFIG_RANDSTRUCT_NONE=y' "$OUT/kernel.config"

test -s "$DIST/vmlinux"
pahole -C task_struct "$DIST/vmlinux" > "$OUT/task_struct.pahole.txt"
grep -q 'sysvsem' "$OUT/task_struct.pahole.txt"
grep -q 'sysvshm' "$OUT/task_struct.pahole.txt"
grep -q '__kabi_reserved4' "$OUT/task_struct.pahole.txt"
grep -Eq 'sysvsem;[[:space:]]+/\*[[:space:]]+3424[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
grep -Eq '__kabi_reserved1;[[:space:]]+/\*[[:space:]]+3424[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
if [[ "$EXTRA_PATCH" == '008.split-sysvshm-across-two-kabi-reserves.patch' ]]; then
	grep -Eq 'sysvshm_next;[[:space:]]+/\*[[:space:]]+3432[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
	grep -Eq 'sysvshm_prev;[[:space:]]+/\*[[:space:]]+3440[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
elif [[ "$EXTRA_PATCH" == '010.allocate-sysvshm-task-state.patch' || \
	"$EXTRA_PATCH" == '010.allocate-sysvshm-task-state.normalized.patch' ]]; then
	grep -Eq '\*[[:space:]]*sysvshm;[[:space:]]+/\*[[:space:]]+3432[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
else
	grep -Eq 'sysvshm;[[:space:]]+/\*[[:space:]]+3432[[:space:]]+16[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
fi
grep -Eq '__kabi_reserved2;[[:space:]]+/\*[[:space:]]+3432[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
grep -Eq '__kabi_reserved3;[[:space:]]+/\*[[:space:]]+3440[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
grep -Eq '__kabi_reserved4;[[:space:]]+/\*[[:space:]]+3448[[:space:]]+8[[:space:]]+\*/' "$OUT/task_struct.pahole.txt"
grep -q 'size: 5184' "$OUT/task_struct.pahole.txt"

nm -n "$DIST/vmlinux" > "$OUT/vmlinux-symbols.txt"
cpufreq_start="$(
	awk '$3 == "cpufreq_acct_update_power" { print "0x" $1; exit }' \
		"$OUT/vmlinux-symbols.txt"
)"
test -n "$cpufreq_start"
cpufreq_stop="$(python3 -c "print(hex(int('$cpufreq_start', 16) + 768))")"
"$KP/prebuilts/clang/host/linux-x86/clang-r536225/bin/llvm-objdump" \
	-d --start-address="$cpufreq_start" --stop-address="$cpufreq_stop" \
	"$DIST/vmlinux" > "$OUT/cpufreq_acct_update_power.disassembly.txt"
grep -q 'task_active_pid_ns' "$OUT/cpufreq_acct_update_power.disassembly.txt"
grep -q '__traceiter_android_vh_cpufreq_acct_update_power' \
	"$OUT/cpufreq_acct_update_power.disassembly.txt"

grep -E 'sysvsem|sysvshm|__kabi_reserved[1-8]|android_(vendor|oem)_data|size:' "$OUT/task_struct.pahole.txt" > "$OUT/task_struct.key-layout.txt"
release_line="$(strings "$DIST/Image" | grep -m1 '^Linux version 6\.12\.23-android16-5-gb2a876903b49-ab14541642-4k ' || true)"
test -n "$release_line"
printf '%s\n' "$release_line" > "$OUT/kernel-release.txt"
cat "$OUT/task_struct.key-layout.txt"
cat "$OUT/kernel-release.txt"
echo "Completed: $(date --iso-8601=seconds)"
